<?php

/**
 * @file
 * This file is run before the request, when the module first loads.
 */

use Composer\Autoload\ClassLoader;
use Drupal\Component\Plugin\PluginManagerInterface;
use Drupal\Core\Config\ConfigFactory;
use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Entity\Plugin\DataType\EntityAdapter;
use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\TypedData\TypedDataManager;
use Drupal\kint\DrupalFieldableEntityPlugin;
use Drupal\kint\KintEventSubscriber;
use Kint\Kint;
use Kint\Parser\BlacklistPlugin;
use Kint\Parser\IteratorPlugin;
use Kint\Renderer\AbstractRenderer;
use Kint\Renderer\RichRenderer;
use Kint\Renderer\TextRenderer;
use Kint\Utils;

// Blacklisted for general dump performance.
BlacklistPlugin::$shallow_blacklist[] = ModuleHandlerInterface::class;
BlacklistPlugin::$shallow_blacklist[] = Connection::class;
BlacklistPlugin::$shallow_blacklist[] = ConfigFactory::class;
BlacklistPlugin::$shallow_blacklist[] = PluginManagerInterface::class;

// Blacklisted for entity dump performance.
BlacklistPlugin::$shallow_blacklist[] = EntityAdapter::class;
BlacklistPlugin::$shallow_blacklist[] = TypedDataManager::class;
IteratorPlugin::$blacklist[] = FieldableEntityInterface::class;
IteratorPlugin::$blacklist[] = FieldItemListInterface::class;
IteratorPlugin::$blacklist[] = FieldItemInterface::class;

// Entity handling plugin.
Kint::$plugins[] = new DrupalFieldableEntityPlugin();
TextRenderer::$parser_plugin_whitelist[] = DrupalFieldableEntityPlugin::class;

// Timestamps.
RichRenderer::$timestamp = '[Y-m-d H:i:s]';
TextRenderer::$timestamp = '[Y-m-d H:i:s]';

// Paths.
Utils::$path_aliases = [DRUPAL_ROOT => '<drupal>'];
foreach (ClassLoader::getRegisteredLoaders() as $vendorDir => $loader) {
  if ($vendorDir && $loader->findFile(\Drupal::class)) {
    Utils::$path_aliases[$vendorDir] = '<vendor>';
    break;
  }
}

// Ideally we want to initialize these settings every time, but occasionally
// the container won't be initialized at this point (Mostly when running updb)
// If the container doesn't exist the event subscriber will initialize it when
// it's constructed.
// If there isn't any config factory in the container when the event subscriber
// is constructed there's nothing we can do, so we ignore the settings entirely.
if (\Drupal::hasContainer() && \Drupal::hasService('config.factory')) {
  KintEventSubscriber::initializeKint(\Drupal::config('kint.settings'));
}

// CSP nonces.
if (\Drupal::hasContainer() && \Drupal::hasService('csp.nonce')) {
  $nonce = \Drupal::service('csp.nonce')->getValue();
  AbstractRenderer::$css_nonce = $nonce;
  AbstractRenderer::$js_nonce = $nonce;
}

/**
 * {@inheritdoc}
 */
function kint_help(string $route_name): string {
  if ($route_name === 'help.page.kint') {
    $out = '<pre>' . file_get_contents(__DIR__ . '/README.md') . '</pre>';

    $out .= <<<EOF
    <p>
      See the <a href="https://kint-php.github.io/kint/" target="_blank">Kint documentation</a> for Kint usage.
    </p>
    EOF;

    return $out;
  }

  return '';
}
